create index on article(id_article);
create index on comment(id_comment);
create index on fish(id_fish);
create index on owner(id_owner);
create index on photo(id_photo);
create index on place(id_place);
create index on survey(id_survey);
create index on users(id_user);
create index on words_for_find(id_words);
