version: '3.3'
services:

  load-balancer-nginx:
    build:
      dockerfile: ./load-balancer/nginx.loadbalancer/DockerFile
    container_name: load-balancer-nginx
    ports:
      - "9999:9999"
    networks:
      - app-network

  db:
    container_name: fishinghelper_container
    image: postgres
    environment:
      - POSTGRES_DB=FishingHelpers
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - app-network
    ports:
      - "5051:5432"

  redis_db:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6051:6379"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: '256M'
    networks:
      - app-network
    command: redis-server --requirepass ""

  config-service:
    build:
      dockerfile: ./config-server/DockerFile
    container_name: config-server-container
    networks:
      - app-network
    ports:
      - "8888:8888"


  auth-service-1:
    build:
      dockerfile: ./auth-service/DockerFile
    container_name: auth-service-container-1
    networks:
      - app-network
    depends_on:
      - db
      - config-service
    environment:
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_HOST=redis_db
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/FishingHelpers
      - SPRING_CLOUD_CONFIG_URL=optional:configserver:http://config-service:8888
    ports:
      - "9091:8081"

  auth-service-2:
    build:
      dockerfile: ./auth-service/DockerFile
    container_name: auth-service-container-2
    networks:
      - app-network
    depends_on:
      - db
      - config-service
    environment:
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_HOST=redis_db
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/FishingHelpers
      - SPRING_CLOUD_CONFIG_URL=optional:configserver:http://config-service:8888
    ports:
      - "9191:8081"

  auth-service-3:
    build:
      dockerfile: ./auth-service/DockerFile
    container_name: auth-service-container-3
    networks:
      - app-network
    depends_on:
      - db
      - config-service
    environment:
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_HOST=redis_db
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/FishingHelpers
      - SPRING_CLOUD_CONFIG_URL=optional:configserver:http://config-service:8888
    ports:
      - "9291:8081"

  user-service-1:
    build:
      dockerfile: ./user-service/DockerFile
    container_name: user-service-container-1
    environment:
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_HOST=redis_db
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/FishingHelpers
      - SPRING_CLOUD_CONFIG_URL=optional:configserver:http://config-service:8888
    depends_on:
      - db
      - config-service
    networks:
      - app-network
    ports:
      - "9090:8080"

  user-service-2:
    build:
      dockerfile: ./user-service/DockerFile
    container_name: user-service-container-2
    environment:
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_HOST=redis_db
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/FishingHelpers
      - SPRING_CLOUD_CONFIG_URL=optional:configserver:http://config-service:8888
    depends_on:
      - db
      - config-service
    networks:
      - app-network
    ports:
      - "9190:8080"

  user-service-3:
    build:
      dockerfile: ./user-service/DockerFile
    container_name: user-service-container-3
    environment:
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_HOST=redis_db
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/FishingHelpers
      - SPRING_CLOUD_CONFIG_URL=optional:configserver:http://config-service:8888
    depends_on:
      - db
      - config-service
    networks:
      - app-network
    ports:
      - "9290:8080"

  admin-service-1:
    build:
      dockerfile: ./admin-service/DockerFile
    container_name: admin-service-container-1
    environment:
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_HOST=redis_db
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/FishingHelpers
      - SPRING_CLOUD_CONFIG_URL=optional:configserver:http://config-service:8888
    depends_on:
      - db
      - config-service
    networks:
      - app-network
    ports:
      - "9092:8082"

  admin-service-2:
    build:
      dockerfile: ./admin-service/DockerFile
    container_name: admin-service-container-2
    environment:
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_HOST=redis_db
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/FishingHelpers
      - SPRING_CLOUD_CONFIG_URL=optional:configserver:http://config-service:8888
    depends_on:
      - db
      - config-service
    networks:
      - app-network
    ports:
      - "9192:8082"

  admin-service-3:
    build:
      dockerfile: ./admin-service/DockerFile
    container_name: admin-service-container-3
    environment:
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_HOST=redis_db
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/FishingHelpers
      - SPRING_CLOUD_CONFIG_URL=optional:configserver:http://config-service:8888
    depends_on:
      - db
      - config-service
    networks:
      - app-network
    ports:
      - "9292:8082"

networks:
  app-network:
    driver: bridge




